In [79]:
import pandas as pd

In [80]:
df=pd.read_csv('data1.csv')

In [81]:
df.head()

Fever  BodyPain  Age  RunnyNose  DiffBreath  InfectionProb
0    102         0   66          0           1              0
1    101         0   18          0           1              1
2    100         0   89          0           0              0
3    100         1   83          0          -1              0
4     99         0   73          1          -1              1

In [82]:
df.tail()

Fever  BodyPain  Age  RunnyNose  DiffBreath  InfectionProb
2567    100         1   43          1           1              0
2568     99         0   68          0          -1              0
2569    101         0   71          1           0              1
2570    101         1   51          1          -1              1
2571    103         1   83          0           1              0

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2572 entries, 0 to 2571
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Fever          2572 non-null   int64
 1   BodyPain       2572 non-null   int64
 2   Age            2572 non-null   int64
 3   RunnyNose      2572 non-null   int64
 4   DiffBreath     2572 non-null   int64
 5   InfectionProb  2572 non-null   int64
dtypes: int64(6)
memory usage: 120.7 KB


In [84]:
df['DiffBreath'].value_counts()

 1    892
-1    842
 0    838
Name: DiffBreath, dtype: int64

In [85]:
df.describe()

Fever     BodyPain          Age    RunnyNose   DiffBreath  \
count  2572.000000  2572.000000  2572.000000  2572.000000  2572.000000   
mean    100.998056     0.501166    49.910575     0.510498     0.019440   
std       2.003982     0.500096    29.319094     0.499987     0.821016   
min      98.000000     0.000000     0.000000     0.000000    -1.000000   
25%      99.000000     0.000000    25.000000     0.000000    -1.000000   
50%     101.000000     1.000000    51.000000     1.000000     0.000000   
75%     103.000000     1.000000    75.000000     1.000000     1.000000   
max     104.000000     1.000000   100.000000     1.000000     1.000000   

       InfectionProb  
count    2572.000000  
mean        0.501944  
std         0.500093  
min         0.000000  
25%         0.000000  
50%         1.000000  
75%         1.000000  
max         1.000000

##Train Test Splitting

In [86]:
import numpy as np

In [87]:
x=df.drop(['InfectionProb'],axis=1)
x

Fever  BodyPain  Age  RunnyNose  DiffBreath
0       102         0   66          0           1
1       101         0   18          0           1
2       100         0   89          0           0
3       100         1   83          0          -1
4        99         0   73          1          -1
...     ...       ...  ...        ...         ...
2567    100         1   43          1           1
2568     99         0   68          0          -1
2569    101         0   71          1           0
2570    101         1   51          1          -1
2571    103         1   83          0           1

[2572 rows x 5 columns]

In [88]:
y=df[['InfectionProb']]

In [89]:
y

InfectionProb
0                 0
1                 1
2                 0
3                 0
4                 1
...             ...
2567              0
2568              0
2569              1
2570              1
2571              0

[2572 rows x 1 columns]

In [90]:
from sklearn.model_selection import train_test_split

In [91]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [92]:
x_train

Fever  BodyPain  Age  RunnyNose  DiffBreath
371     103         0    3          0          -1
1787    104         0   56          1           0
622     101         1   96          1           1
2084    101         0   58          1          -1
759      99         0   20          0          -1
...     ...       ...  ...        ...         ...
962     102         0   69          0           0
2135    100         1   66          1           0
144     101         0   69          1          -1
463      98         0   98          1           1
40       98         0   35          1           0

[2057 rows x 5 columns]

In [93]:
x_test

Fever  BodyPain  Age  RunnyNose  DiffBreath
1060    100         0   74          0           0
1698    103         1    3          1           1
1443    101         0   19          0          -1
1152    102         1   22          0           0
2080    104         1   54          1           1
...     ...       ...  ...        ...         ...
1633    102         0   68          0           1
1874    104         1   60          0          -1
673     103         1   48          1           1
596     101         1   65          1          -1
32      101         0   40          0           1

[515 rows x 5 columns]

In [94]:
X_train=x_train.to_numpy()
X_train

array([[103,   0,   3,   0,  -1],
       [104,   0,  56,   1,   0],
       [101,   1,  96,   1,   1],
       ...,
       [101,   0,  69,   1,  -1],
       [ 98,   0,  98,   1,   1],
       [ 98,   0,  35,   1,   0]], dtype=int64)

In [95]:
X_train

array([[103,   0,   3,   0,  -1],
       [104,   0,  56,   1,   0],
       [101,   1,  96,   1,   1],
       ...,
       [101,   0,  69,   1,  -1],
       [ 98,   0,  98,   1,   1],
       [ 98,   0,  35,   1,   0]], dtype=int64)

In [96]:
Y_train=y_train.to_numpy().reshape(2057,)
Y_train

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [97]:
X_test=x_train.to_numpy()
X_test

array([[103,   0,   3,   0,  -1],
       [104,   0,  56,   1,   0],
       [101,   1,  96,   1,   1],
       ...,
       [101,   0,  69,   1,  -1],
       [ 98,   0,  98,   1,   1],
       [ 98,   0,  35,   1,   0]], dtype=int64)

In [98]:
Y_test=y_test.to_numpy().reshape(515,)
Y_test

array([0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,

In [99]:
y_test

InfectionProb
1060              0
1698              1
1443              1
1152              0
2080              0
...             ...
1633              1
1874              0
673               0
596               1
32                1

[515 rows x 1 columns]

In [100]:
from sklearn.linear_model import LogisticRegression

In [101]:
model=LogisticRegression()

In [102]:
model.fit(X_train,Y_train)

LogisticRegression()

In [103]:
model.predict([[100,1,22,1,1]])

array([1], dtype=int64)

In [104]:
model.predict([[103,0,8,0,0]])

array([0], dtype=int64)

In [105]:
model.score(X_train,Y_train)

0.5333009236752553

In [106]:
model.predict_proba([[100,1,22,-1,1]])

array([[0.47035994, 0.52964006]])

In [107]:
infprob=model.predict_proba([[100,1,22,-1,1]])[0][1]
infprob

0.5296400584372797

In [108]:
inputfeatures=[100,1,22,-1,1]
infprob=model.predict_proba([inputfeatures])[0][1]
infprob


0.5296400584372797

In [109]:
clf=LogisticRegression()

In [110]:
clf.fit(x_train,y_train)

c:\users\atif khan\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [111]:
clf.predict([[100,1,22,1,1]])

c:\users\atif khan\appdata\local\programs\python\python38\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [112]:
clf.predict_proba([[100,1,22,-1,1]])

c:\users\atif khan\appdata\local\programs\python\python38\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([[0.47035994, 0.52964006]])

In [113]:
Z_test=clf.predict(x_test)
Z_test

array([0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,

In [114]:
x_test

Fever  BodyPain  Age  RunnyNose  DiffBreath
1060    100         0   74          0           0
1698    103         1    3          1           1
1443    101         0   19          0          -1
1152    102         1   22          0           0
2080    104         1   54          1           1
...     ...       ...  ...        ...         ...
1633    102         0   68          0           1
1874    104         1   60          0          -1
673     103         1   48          1           1
596     101         1   65          1          -1
32      101         0   40          0           1

[515 rows x 5 columns]

In [115]:
y_test

InfectionProb
1060              0
1698              1
1443              1
1152              0
2080              0
...             ...
1633              1
1874              0
673               0
596               1
32                1

[515 rows x 1 columns]

In [116]:
import joblib

In [117]:
joblib.dump(model,'file')

['file']